blog/urls.py
from django.contrib.contenttypes.fields import create_generic_related_manager
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views
from .feeds import LatestPostsFeed
from blog.views import *

app_name = 'blog'

urlpatterns = [ 
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag' ),
    #  path('', views.PostListView.as_view(), name= 'post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('create/', create_post, name='create_post'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps' : sitemaps}, name= 'django.contrib.sitemaps.views.sitemaps')
    
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(status='published')
            

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(null=True)
    created = models.DateTimeField(null=True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.BooleanField(default=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from .models import Comment, Post
from django import forms  #django has two base classes to build form 1. Form and 2. ModelForm

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title', 'body', 'status',  'tags')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'body': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})

        }

    


            

blog/views.py
from django.core import paginator
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm 
from django.core.mail import send_mail
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.http import HttpResponseRedirect

from .forms import (
    PostForm
)


def post_share(request, post_id):  #it retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():   #if all fields contain valid data then it returnd true else returns false
            cd = form.cleaned_data   #if form is valid then it retrieve validated data 
            post_url = request.build_absolute_uri(post.get_absolute_url())
 
            subject = '{} ({}) recommends your reading  " {} "'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True

    else:
            form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form':form, 'sent':sent})


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tag__in=[tag])

    paginator = Paginator(object_list, 3)  #it have 3 posts in each page
    page = request.GET.get('page')  #it indicates the current page number
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    return render(request, 'blog/post/list.html', { 'page': page, 'posts': posts, 'tag' : tag})
    

    

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
     
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    #List of similar posts

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]



    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new _comment' : new_comment, 'comment_form' : comment_form ,  'similar_posts': similar_posts})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    pagination_by = 3
    template_name = 'blog/post/list.html'

    

#create new post
def create_post(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            form.save_m2m()
            return HttpResponseRedirect(instance.get_absolute_url())
    context = {
    'form': form
    }

    return render(request, "blog/post/post_form.html", context)




    

 

# Create your views here.

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title> {% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>
<body>
  
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Pet Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link active" href="#">Login</a>
        <a class="nav-item nav-link active" href="#">Signin</a>
        <a class="nav-item nav-link active" href="{% url 'create_post' %}">New Post</a>
      </div>
    </div>
  </nav>
    <div id="content">
        {% block content %}
        {% endblock %}
      </div>
      
        <h5>Pet Blog</h5>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        <p><a href="{% url "blog:post_feed" %}"> Subscribe to my feed </a></p>
        
        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}
        
        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
        {% for post in most_commented_posts %}
          <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
          </li>
        {% endfor %}
        </ul>
    </div>

    
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }} {% endblock %}

{% block content %}

  <h1>{{ post.title}}</h1>
  <p class="date">
      Published {{ post.publish}} by {{post.author}}

  </p>
  {{post.body|markdown}}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Share this post
    </a>
  </p>

  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}

  {% with comments.count as total_comments %}
     <h2>
       {{ total_comments }} comment {{ total_comments|pluralize }}
     </h2>
  {% endwith %}

  {% for comment in comments %}
    <div class="comment">
      <p class="info">
         Comment {{ forloop.counter }} by {{ comment.name }}
      </p>
       {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p> There are no comments yet.</p>
  {% endfor %}

  {% if new_comments %}
    <h2> Your comment has been added. </h2>
    {% else %}
      <h2> Add a new comment</h2>
      <form action="." method="post">
        {{ comment_form.as_p}}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
      </form>
    {% endif %}
{% endblock %}
    

blog/templates/blog/post/latest_posts.html
<ul>
    {% for posts in latest_posts %}
       <li>
           <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
       </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} Pet Blog {% endblock %}

{% block content %}
  <h1>Pet Blog</h1>
  

  {% if tag %}
    <h2> Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts%}
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col">
  <div class="card border-primary mb-3"  style="width: 18rem">
    <div class="card-body">
    <h2 style="color:red">
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h2>
    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    
    
     {{ post.body|markdown|truncatewords_html:30}}  <!--truncate the strings after a certain number of words -->
     </div>
     </div> 
     </div>
     </div>
  {% endfor %}
  {% include "pagination.html" with page=posts %}

{% endblock %}

blog/templates/blog/post/post_form.html
{% extends 'blog/base.html' %}
{% block title %} Form {% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
         {{form.as_p}}
         {% csrf_token %}
         <input type="submit" class="btn btn-primary" value="CREATE"> 
    </form>

{% endblock %}    

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Share a post {% endblock %}

{% block content %}
   {% if sent %}
      <h1>E-mail successfully sent</h1>
      <p>
          "{{post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
      </p>
    {% else %}
       <h1> Share "{{ post.title }}" by e-mail</h1>
       <form action="." method="post">
           {{ form.as_p}}
           {% csrf_token %}
           <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
           <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages}}.
        </span>
            {% if page.has_next %}
               <a href="?page={{ page.next_page_number }}">Next </a>
            {% endif %}
    </span>
</div>